In [25]:
import numpy as np
import pandas as pd
from sklearn import svm
from sklearn import datasets
from sklearn.model_selection import train_test_split

In [14]:
cancer = datasets.load_breast_cancer()

In [24]:
print("Labels:",cancer.target_names)

Labels: ['malignant' 'benign']


In [52]:
x_train,x_test,y_train,y_test=train_test_split(cancer.data,cancer.target,test_size=0.3,random_state=90)

In [53]:
x_train

array([[1.361e+01, 2.498e+01, 8.805e+01, ..., 1.184e-01, 2.651e-01,
        7.397e-02],
       [1.462e+01, 2.402e+01, 9.457e+01, ..., 6.946e-02, 2.522e-01,
        7.246e-02],
       [1.129e+01, 1.304e+01, 7.223e+01, ..., 8.750e-02, 2.733e-01,
        8.022e-02],
       ...,
       [1.296e+01, 1.829e+01, 8.418e+01, ..., 6.608e-02, 3.207e-01,
        7.247e-02],
       [1.200e+01, 2.823e+01, 7.677e+01, ..., 7.116e-02, 2.447e-01,
        8.194e-02],
       [2.034e+01, 2.151e+01, 1.359e+02, ..., 2.685e-01, 5.558e-01,
        1.024e-01]])

In [54]:
y_test

array([1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1])

In [55]:
x_test

array([[1.230e+01, 1.902e+01, 7.788e+01, ..., 3.983e-02, 2.554e-01,
        7.207e-02],
       [1.225e+01, 2.244e+01, 7.818e+01, ..., 6.335e-02, 3.100e-01,
        8.203e-02],
       [1.270e+01, 1.217e+01, 8.088e+01, ..., 8.224e-02, 2.775e-01,
        9.464e-02],
       ...,
       [1.088e+01, 1.562e+01, 7.041e+01, ..., 7.966e-02, 2.581e-01,
        1.080e-01],
       [1.944e+01, 1.882e+01, 1.281e+02, ..., 2.060e-01, 3.266e-01,
        9.009e-02],
       [1.166e+01, 1.707e+01, 7.370e+01, ..., 4.262e-02, 2.731e-01,
        6.825e-02]])

In [56]:
classifier=svm.SVC()

In [57]:
classifier.fit(x_train,y_train)

SVC()

In [58]:
y_pred=classifier.predict(x_test)

In [59]:
y_pred

array([1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1])

In [62]:
result=pd.DataFrame(y_test,columns=["Test"])

In [63]:
result["Predicted"]=y_pred

In [64]:
result

Test  Predicted
0       1          1
1       1          1
2       1          1
3       1          1
4       1          1
..    ...        ...
166     1          1
167     1          0
168     1          1
169     0          0
170     1          1

[171 rows x 2 columns]

In [65]:
result["error"]=result["Test"]-result["Predicted"]

In [66]:
result["sqerr"]=result["error"]**2
result["rms"]=np.sqrt(result["sqerr"])

In [67]:
overall_rms=np.sqrt(result["sqerr"].mean())

In [68]:
overall_rms

np.float64(0.2961744388795462)

In [69]:
from sklearn import metrics

In [71]:
metrics.accuracy_score(y_test,y_pred)

0.9122807017543859